config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  root "messages#index"
  resources :messages,   only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get :old_message
      get :rank_message
    end
    resources :comments,   only: [:create]
  end
  post    '/like/:message_id' => 'likes#like', as: 'like'
  delete  '/like/:message_id' => 'likes#unlike', as: 'unlike'
  get     '/tag/:tag_name' => 'tags#index', as: 'tags'
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many   :images,           dependent: :destroy
  has_many   :comments
  has_many   :likes,            dependent: :destroy
  has_many   :liked_users,      through: :likes, source: :user
  has_many   :message_tags,     dependent: :destroy
  has_many   :tags,             through: :message_tags
  
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :tags,   allow_destroy: true
  validates :content, presence: true, length: {maximum: 40} 
  is_impressionable counter_cache: true
  validates_associated :images
  validates :images, presence: true

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def rnking  
    Message.find(Like.group(:message_id).order('count(message_id) desc').limit(10).count(:message_id).keys)
  end

  def save_messages(tag)
    current_tag = Tag.pluck(:tag_name) unless self.tags.nil?
    old_tag = current_tag - tag
    new_tag = tag - current_tag

    old_tag.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end

    new_tag.each do |new_name|
      message_tag = Tag.find_or_create_by(tag_name: new_name )
      self.tags << message_tag
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :move_to_index, except: [:index, :old_messages, :show]

  def index
    @messages = Message.includes(:user).order('created_at DESC').page(params[:page]).per(12)
    @list_tags = Tag.unscoped.joins(:message_tags).group(:id, :tag_id).order('count(tag_id) DESC')
    # @list_tags = Tag.joins(:message_tags).group(:tag_id).order('count(tag_id) DESC')
    # @most_views = Message.order("impressions_count DESC").take(10)
  end
  
  def old_message
    @list_tags = Tag.unscoped.joins(:message_tags).group(:id, :tag_id).order('count(tag_id) DESC')
    @old_messages = Message.includes(:user).order('created_at ASC').page(params[:page]).per(12)
  end

  def rank_message
    @list_tags = Tag.unscoped.joins(:message_tags).group(:id, :tag_id).order('count(tag_id) DESC')
    @all_ranks = Message.find(Like.group(:message_id).order('count(message_id) desc').limit(10).count(:message_id).keys)
  end

  def new
    @message = Message.new
    @message.images.new
  end 

  def create
    @message = Message.new(message_params)
    tag_list = params[:message][:tag][:tag_name].split(",")     
    if @message.valid?
       @message.save_messages(tag_list) if params[:message][:tag][:tag_name].presence
       @message.save
       redirect_to root_path
    else  
      flash.now[:alert]= @message.errors.full_messages
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
    @comment = Comment.new
    @comments = @message.comments.includes(:user).order("created_at DESC")
    @like = Like.new
    @page_views = @message.impressionist_count
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if  @message.update(message_params)
      redirect_to root_path
    else  
      flash.now[:alert]= @message.errors.full_messages
      render :new
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to root_path
  end

  def rnking
    @all_ranks = Message.rnking
  end

  private 

    def message_params
      params.require(:message).permit(:content, :tag_ids, images_attributes: [:image, :_destroy, :id, :tags]).merge(user_id: current_user.id)
    end

    def move_to_index
      redirect_to action: :index unless logged_in?
    end
    
end  

app/views/messages/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to " Home", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo02", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      %li.nav-item.active.dropdown-btn.nav-link.relative
        - if logged_in?
          =current_user.name   
          %ul.dropdown
            %li
              = link_to "マイページ", user_path(current_user), class: "hiddon"
            %li
              = link_to "投稿", new_message_path, class: "hiddon" 
            %li
              = link_to "ログアウト", logout_path, method: :delete, class:"hiddon"
        - else
          USER
          %ul.dropdown
            %li
              = link_to "新規登録", new_user_path, class:"hiddon"
            %li
              = link_to "ログイン", login_path, class:"hiddon"
        -# %span.sr-only (current) 
      -# %li.nav-item
      -#   = link_to "Link", "#", class:"nav-link"
      -# %li.nav-item
      -#   = link_to "Disabled", "#", class: "nav-link disabled"
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{:placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search


-# %nav.navbar.navbar-expand-lg.navbar-light.bg-light
-#   =link_to " Navbar", "#", class: "navbar-brand"
-#   %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo02", "data-toggle" => "collapse", :type => "button"}
-#     %span.navbar-toggler-icon
-#   #navbarTogglerDemo02.collapse.navbar-collapse
-#     .navbar-nav.mr-auto.mt-2.mt-lg-0
-#       %ui.nav-item.active
-#         = link_to "Home", "#", class: "nav-link" 
-#         -# %span.sr-only (current)
-#           %ll.nav-item.active
-#             = link_to "Home", "#", class: "nav-link"
-#           %li.nav-item.active
-#             = link_to "Home", "#", class: "nav-link"
-#       %ui.nav-item
-#         = link_to "Link", "#", class:"nav-link"
-#       %ui.nav-item
-#         = link_to "Disabled", "#", class: "nav-link disabled"
-#     %form.form-inline.my-2.my-lg-0
-#       %input.form-control.mr-sm-2{:placeholder => "Search", :type => "search"}/
-#       %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/messages/_main_chat.html.haml
.main
  .messages
    .message__normal
      = render @messages
    = paginate(@messages)

  -# = paginate(@messages)
  
  -# - @list_tags.each do |tag|
  -#   .message.message__type
  -#     .message__content
  -#       .message__content__image
  -#         = link_to  message_path(message.id) do
  -#           - message.images.first(1).each do |image|
  -#             = image_tag image.image.thumb.url, height: "100%", width: "100%"
  -#       .message__content__content
  -#         %p#text
  -#           = message.content
  -# .message
  -#   .message__content
  -#     .message__content__image
  -#       000
  -#     .message__content__content
  -#       %p#text ya----ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    

app/views/messages/_message.html.haml
.message
  .message__content
    .message__content__image
      = link_to  message_path(message.id) do
        - message.images.first(1).each do |image|
          = image_tag image.image.thumb.url, height: "100%", width: "100%"
    .message__content__content
      %p#text
        = message.content

app/views/messages/_side_bar.html.haml
.groups
  .group
    .list_tag
      %ul
        %h5 動物一覧
        - if !@list_tags.blank?
          - @list_tags.each do |tag|
            .group_type
              - if !tag.blank?
                .group__data{data: {name: tag.tag_name}}
                  %li
                    = link_to "#{tag.tag_name}", tags_path(tag.tag_name)  #, remote: true
                = "(#{tag.message_tags.count})"
    .list_tag
      %ul
        %h5 並び替え
        %li
          .list_tag__new
            = link_to "新着順", root_path
        %li 
          .list_tag__old
            = link_to "古い順", old_message_messages_path
            
        %li
          .list_tag__rank
            = link_to "いいねが多い順", rank_message_messages_path
            
        
  -# .sorting
   
  -#  
  -# .message__tab.message__btn__normal
  -#   新着順
  -# .message__tab.message__btn__rank
  -#   お気に入り順
  -# - @all_ranks.each do |message|
  -#   = message.id
  -# - @most_views.each do |message|
  -#   = message.id
    

app/views/messages/edit.html.haml
.message__new
  = render "header"

  .message__new__post
    %p.post__title 編集する
    = form_for @message do |f|
      .new-wrapper
        .new-wrapper__main
          .new-wrapper__main__post
            #image-box__edit
              %label{class: "flexbox", action: request.path}
                .new-wrapper__main__image
                  %i{class: "fas fa-camera"}

                    = f.fields_for :images do |i|
                      = i.file_field :image, {class: "file-field", name: "message[images_attributes][#{@message.images.length}][image]", id: "message_images_attributes_#{@message.images.length}_image"}
                      = i.file_field :image, {class: "file-field", type: "file"}
                      - if @message.persisted?
                        = i.check_box :_destroy, {class: "hidden"}
              
              .new-wrapper__main__title 投稿画像
              - @message.images.each_with_index do |image, index|
                .item-image{ id: "item-image#{index}" }
                  .item-image__content
                    .item-image__content--icon
                      = image_tag image.image.url, width: "110", height: "100", alt: "preview"
                  .item-image__operetion
                    .item-image__operetion--delete--edit{ index: "#{index}" }
                      削除
          .new-wrapper__main__content
            = f.text_area :content, {class: "new-wrapper__main__content--text", placeholder: "文字を入力してください" }
          .new-wrapper__main__tag
            Type:
            = f.collection_select :tag_ids, Tag.all, :id, :tag_name  
            %br
            = f.fields_for :tag do |i|
              = i.text_field :tag_name, {class: "other__choise", placeholder: "何か種類があれば入力してください" }
          .new-wrapper__main__submit
            = f.submit "送信する", {class:"new-wrapper__main__submit--btn"}

app/views/messages/index.html.haml
.wrapper
  = render "header"
  = render "side_bar"
  = render "main_chat"

app/views/messages/index.js.erb
<%- @list_tags.each do |tag| %> 
  <div class="message.message__rank" >
    <div class="message__content">
      <%= link_to message_path(@message.id) %>
        <%- %>
    </div>
  </div>
            = link_to  message_path(message.id) do
              - message.images.first(1).each do |image|
                = image_tag image.image.thumb.url, height: "100%", width: "100%"
          .message__content__content
            %p#text
              = message.content

$(".messages").html("<%= j(render group) ) %>")


<% $("#link-<%= @message.id %>").html("<%= j(render partial: 'likes/like', locals: { message: @message, likes: @likes, like: @like }) %>"); %>
<% $(".user__p").html("<%= escape_javascript(render('users/unfollow')) %>"); %>
<% $("#follwers").html('<%= @user.followers.count'); %>

app/views/messages/new.html.haml
.message__new
  = render "header"

  .message__new__post
    %p.post__title 投稿する

    = form_for @message do |f|
      .new-wrapper
        .new-wrapper__main
          .new-wrapper__main__post
            #image-box
              %label{class: "flexbox", action: request.path}
                .new-wrapper__main__image
                  %i{class: "fas fa-camera"}
                    -#   .new-wrapper__main__image-field__text
                    -#     ドラッグアンドドロップ
                    -#     %br  name: "message[imeges_attributes][][image]"
                    -#     またはクリックしてファイルをアップロード
                    = f.fields_for :images do |i|
                      = i.file_field :image, {class: "file-field", type: "file"}
                -# = f.fields_for :images do |i|
                -#   = i.file_field :image, {class: "file-field", type: "file"}
              .new-wrapper__main__title
                投稿画像
          .new-wrapper__main__content
            = f.text_area :content, {class: "new-wrapper__main__content--text", placeholder: "文字を入力してください" }
            -# = f.text_area :content, {class: "new-wrapper__main__input-textarea", placeholder: "商品の説明(必須 1,000文字以内)\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"}
          .new-wrapper__main__tag
            Type:
            = f.collection_select :tag_ids, Tag.all, :id, :tag_name  
            %br
            = f.fields_for :tag do |i|
              = i.text_field :tag_name, {class: "other__choise", placeholder: "何か種類があれば入力してください" }
          .new-wrapper__main__submit
            = f.submit "送信する", {class:"new-wrapper__main__submit--btn"}

app/views/messages/old_message.html.haml
.wrapper
  = render "header"
  = render "side_bar"
  .main
    .messages
      .message__old
        - @old_messages.each do |message|
          = render message
      = paginate(@old_messages)

app/views/messages/rank_message.html.haml
.wrapper
  = render "header"
  = render "side_bar"
  .main
    .messages
      .message__rank
        - @all_ranks.each do |message|
          = render message

app/views/messages/show.html.haml
= render "header"
-# = render "side_bar"
.message_show
  .show
    .more
      %span
        =image_tag 'arrow_top.png'
      %ul.more__list 
        %li
          = link_to "削除", message_path(@message.id), method: "delete"
          = link_to "編集", edit_message_path(@message.id)
    .show__image
      - @message.images.each do |image|
        = image_tag image.image.url, {class: "show__image__tag", width: "100px", height: "200px"}
    
    .show__message
      = simple_format(@message.content)
    
      .show__message__user
        .show__message__user__info
          .show__message__user__info__name 
            = link_to "投稿者: #{@message.user.name}", user_path(@message.user.id)
          .show__message__user__info__time
            = @message.created_at.strftime("%Y年%m月%d日 %H時%M分")

    .like{ id: "link-#{@message.id}"}
      = render partial: "likes/like", locals: {message: @message}

    .show__comment
      -if current_user
        =form_for [@message, @comment] do |f|
          =f.text_area :text, placeholder: "コメントする", rows: "2", class: "show__comment__text"
          =f.submit "SENT", class: 'show__comment__form'
      - else 
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    .show__comments
      %h6.show__title <コメント一覧>
      .show__comments__comment
        - if @comments 
          - @comments.each do |comment|
            .comment 
              %strong 
                =link_to "#{comment.user.name}:", "#", class: "show__comments__comment__name"
              .show__comments__comment__text
                = simple_format(comment.text)
  
    