config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  root "messages#index"
  resources :messages,   only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get :old_message
      get :rank_message
    end
    resources :comments,   only: [:create]
  end
  post    '/like/:message_id' => 'likes#like', as: 'like'
  delete  '/like/:message_id' => 'likes#unlike', as: 'unlike'
  get     '/tag/:tag_name' => 'tags#index', as: 'tags'
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user  
  belongs_to :message
  validates_uniqueness_of :message_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    @like = Like.create(user_id: current_user.id, message_id: params[:message_id])
    @likes = Like.where(message_id: params[:message_id])
    @messages = Message.includes(:user)
  end

  def unlike
    @like = Like.find_by(user_id: current_user.id, message_id: params[:message_id])
    @like.destroy
    @likes = Like.where(message_id: params[:message_id])
    @messages = Message.includes(:user)
  end

  private
  def set_variables
    @message = Message.find(params[:message_id])
  end

end

app/views/likes/_like.html.haml
- if logged_in?
  - if message.like_user(current_user.id) || message.user.id == current_user.id
    = button_to unlike_path(message.id), method: :delete, id: "like-button", remote: true do
      いいね数
      %i{class: "fas fa-heart"}
        = message.likes.count
  - else  
    = button_to like_path(message.id), method: :post, id: "like-butto7n", remote: true do
      いいねと思ったら押してください
      %i{class: "far fa-heart"}
        = message.likes.count
- else 
  -# %i{class: "far fa-heart"}
  %i{class: "fas fa-heart"}
    = message.likes.count

-# = message.likes.count.to_s
-# .like-link{id: "like-link-#{@message.id}"}
-#   -if current_user.likes.find_by(message_id: @message.id)
-#     = link_to unless_path(@message.id), method: :delete, remoto: true do
-#       .like-link__delete__btn{id: "delete__btn#{@message.id}"}
-#         = @message_likes.count.to_s
-#   - else  
-#     = link_to like_path(@message.id), method: :post, remoto: true
-#       .like-link__delete__btn{id: "delete__btn#{@message.id}"}
-#         = @message.likes.count.to_s

app/views/likes/like.js.erb
$("#link-<%= @message.id %>").html("<%= j(render partial: 'likes/like', locals: { message: @message, likes: @likes, like: @like }) %>");

app/views/likes/unlike.js.erb
$("#link-<%= @message.id %>").html("<%= j(render partial: 'likes/like', locals: { message: @message,  likes: @likes }) %>");