config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  root "messages#index"
  resources :messages,   only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get :old_message
      get :rank_message
    end
    resources :comments,   only: [:create]
  end
  post    '/like/:message_id' => 'likes#like', as: 'like'
  delete  '/like/:message_id' => 'likes#unlike', as: 'unlike'
  get     '/tag/:tag_name' => 'tags#index', as: 'tags'
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :validatable
  attr_accessor :remember_token
  has_secure_password validations: true
  
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 8}, allow_nil: true
  mount_uploader :pfofiel, ImageUploader, if: :pfofiel
  has_many :messages
  has_many :comments
  has_many :likes,  dependent: :destroy
  has_many :liked_messages, through: :likes, source: :message
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:  :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy    
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

   # 渡された文字列のハッシュ値を返す
   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                            BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #永続セッションのためにユーザーをデータベースに記憶する。
  def remember
    self.remember_token = User.new_token
    self.update_attribute(:remember_digest, User.digest(remember_token))
  end

  #渡されたトークンがダイジェストに一致したらtrueを返す

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザのログイン情報を破棄する
  def forget
    self.update_attribute(:remember_digest, nil)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザのフォローを解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # def followers?(other_user)
  #   following?(other_user) &&  followers.include?(other_user)
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @messages = @user.messages
    @users = @user.following
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:success] = "ようこそ" 
      redirect_to root_path
    else   
      render 'new'
    end
  end

  #GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH /users/:id
  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
    redirect_to root_path
    flash[:notice] = "プロフィールを更新しました"
    else  
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_url
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private
    def user_params
      params.require(:user).permit(:pfofiel, :name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in? 
        store_location
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user? @user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  =f.hidden_field :followed_id, value: @user.id
  =f.submit "フォロー", {clsss: "btn btn-primary"}

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
  -if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

-# https://docs.google.com/document/d/10CvPolWYUd_eqafZeeFXEpZdhq5_Yyai6h93TOx1sNY/edit#
-# https://docs.google.com/document/d/1BKB7kFp_erJAc63W4BKdzNgRwe7_OvO4MlECXT_iaJA/edit#heading=h.uc9r1bu1xm1f
-# https://docs.google.com/document/d/10CvPolWYUd_eqafZeeFXEpZdhq5_Yyai6h93TOx1sNY/edit#heading=h.dudefr7d7aao

app/views/users/_following.html.haml
.user_show__image__posts
  - @users.each do |user|
    .user_show__image__post
      = link_to  user_path(user.id) do
        = image_tag user.pfofiel, {class: "show__image__tag" , height: "100%" ,width: "100%"}
    .user_show__image__content
      = @user.name

app/views/users/_unfollow.html.haml
-# - binding.pry
=form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }, remote: true) do |f|
  = f.submit "フォロー解除", class: "btn"

-# =form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
-# <%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
-#             html: { method: :delete }, local: true) do |f| %>

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", logout_path, method: "delete", class: 'btn'
      = link_to "戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for @user do |f|
        .field#field__image
          .field-label
            %label{class: "flexbox", action: request.path}
              .field-label__image
                - if !@user.pfofiel.file.nil?
                  /-binding.pry
                  = f.file_field :pfofiel, {class: "file-field",id: "pfofiel__image", type: "file"}
                  .pfofiel__item
                    .item-image__content
                      .item-image__content--icon
                        = image_tag @user.pfofiel, width: "150px", height: "150px"
                      .item-image__operetion
                        .pfofiel__item--delete{ index: "0" } 削除
                - else
                  %p.pfofiel--text プロフィール写真を載せてください
                  %f{class: "fas fa-camera pfofiel"}
                  = f.file_field :pfofiel, {class: "file-field",id: "pfofiel__image", type: "file"}

        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (英数字8文字以上)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/new.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Create Account
      %h5 新規アカウントの作成
      = link_to "ログイン", login_path, class: 'btn'
      = link_to "トップページ", root_path, class: 'btn'
    .account-page__inner--right.user-form
      = form_for @user do |f|
        = render 'shared/error_messages'
        .field#field__image
          .field-label
            %label{class: "flexbox", action: request.path}
              -# =label :プロフィール写真を載せてください,{class: "flexbox", action: request.path}
              .field-label__image
                %p.pfofiel--text プロフィール写真を載せてください
                %f{class: "fas fa-camera pfofiel"}
                = f.file_field :pfofiel, {class: "file-field",id: "pfofiel__image", type: "file"}
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (英数字8文字以上)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .actions
          = f.submit "Create Account", class: 'btn'

app/views/users/show.html.haml
= render "messages/header"
.row
  .user__profiel
    - if @user.pfofiel.presence
      .user__profiel__image
        = image_tag @user.pfofiel.url, height:'100%' ,width: "100%"
    - else 
      .user__profiel__image
        = image_tag "member_photo_noimage_thumb.png", {height: "100%" ,width: "100%"}
    .user__profiel__content
      .user__profiel__content--name
        = @user.name
      - if logged_in? && current_user.id == @user.id
        .botton__edit__delete
          = button_to "削除", @user, method: :delete, class: "botton__edit__delete--btn"
          = button_to "編集", edit_user_path(@user.id), method: 'get', class: "botton__edit__delete--btn"
          = button_to "投稿", new_message_path, method: 'get', class: "botton__edit__delete--btn"
      .user__profiel__content--count
        投稿した回数 
        %br
        = @user.messages.count
      .user__profiel__content--follow
        = render 'follow_form' if logged_in?
        -#  render partial: "likes/like", locals: {message: @message}
    .user__profiel__follow
      = render 'shared/stats'
    
  .user_show__image.user_show__posts
    - @messages.each do |message|
      .user_show__image__posts
        - message.images.first(1).each do |image|
          .user_show__image__post
            = link_to  message_path(message.id) do
              = image_tag image.image.url, {class: "show__image__tag" , height: "100%" ,width: "100%"}
          .user_show__image__content
            .user_show__image__content--text
              =message.content
            -# - if logged_in?
            -#   .like{ id: "link-#{message.id}"}
            -#     = render partial: "likes/like", locals: {message: message}
            .user_show__image__content--time
              = message.created_at.strftime("%Y年%m月%d日 %H時%M分")

  -# .user_show__image.user_show__follwing
  -#   - @users.each do |user|
  -#     .user_show__image__posts
  -#       .user_show__image__post
  -#         = link_to  user_path(user.id) do
  -#           - if user.pfofiel.presence
  -#             = image_tag user.pfofiel.url, {class: "show__image__tag" , height: "100%" ,width: "100%"}
  -#           - else 
  -#             %P.noimage NO IMAGE
  -#       .user_show__image__content
  -#         .user_show__image__content--text
  -#           = user.name
  -#         .user__profiel__content--follow

app/views/users/show_follow.html.haml
= render "messages/header"
.row
  .user__profiel
    - if @user.pfofiel.presence
      .user__profiel__image
        = image_tag @user.pfofiel.url, height:'100%' ,width: "100%"
    - else 
      .user__profiel__image
        = image_tag "member_photo_noimage_thumb.png", {height: "100%" ,width: "100%"}
        -# %P.noimage NO IMAGE
    .user__profiel__content
      .user__profiel__content--name
        = @user.name
      - if logged_in? && current_user.id == @user.id
        .botton__edit__delete
          = button_to "削除", @user, method: :delete, class: "botton__edit__delete--btn"
          = button_to "編集", edit_user_path(@user.id), method: 'get', class: "botton__edit__delete--btn"
          = button_to "投稿", new_message_path, method: 'get', class: "botton__edit__delete--btn"
      .user__profiel__content--count
        投稿した回数 
        %br
        = link_to @user.messages.count, @user
      - unless @current_user == @user
        .user__profiel__content--follow
          = render 'follow_form'
    .user__profiel__follow
      = render 'shared/stats'

  .user_show__image.user_show__follwing
    - @users.each do |user|
      .user_show__image__posts
        .user_show__image__post
          = link_to  user_path(user.id) do
            - if user.pfofiel.presence
              = image_tag user.pfofiel.url, {class: "show__image__tag" , height: "100%" ,width: "100%"}
            - else 
              = image_tag "member_photo_noimage_thumb.png", {class: "show__image__tag" , height: "100%" ,width: "100%"}
        .user_show__image__content
          .user_show__image__content--text
            Name:
            = user.name
          -# .user__profiel__content--follow
          -#   - if @current_user == @user
          -#     -if current_user.followers?(user)
          -#       =form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }, remote: true) do |f|
          -#         = f.submit "フォロー解除", class: "btn"
              -# - else
              -#   = form_for(current_user.active_relationships.build, remote: true) do |f|
              -#     =f.hidden_field :followed_id, value: user.id
              -#     =f.submit "フォロー", {clsss: "btn btn-primary"}

-# https://docs.google.com/document/d/1aGdECO1Zq7J8AO3DEyq_G2jBpge_7kN45I5fXbl98-A/edit?usp=drivesdk
-# https://docs.google.com/document/d/10CvPolWYUd_eqafZeeFXEpZdhq5_Yyai6h93TOx1sNY/edit?usp=sharing
-# https://docs.google.com/document/d/1BKB7kFp_erJAc63W4BKdzNgRwe7_OvO4MlECXT_iaJA/edit?usp=sharing
-# https://docs.google.com/document/d/10CvPolWYUd_eqafZeeFXEpZdhq5_Yyai6h93TOx1sNY/edit?usp=sharing
-# https://docs.google.com/document/d/10CvPolWYUd_eqafZeeFXEpZdhq5_Yyai6h93TOx1sNY/edit#